
PROGRAM _INIT
	aiLogoAxisActPos;
	diMagazineEmpty;
	diCapAtPickup;
	diCapPusherForward;
	diCapPusherBack;
	diPickupArmBack;
	diPickupArmForward;
	diCapGripperVacuum;
	diCapOnLogoConveyor;
	diCapExitLogoConveyor;
	diLogoStamperBack;
	diLogoStamperForward;
	aoLogoConveyorSetSpeed;
	doCapPusher;
	doPickupArmForward;
	doPickupArmBack;
	doCapGripperPick;
	aoLogoAxisSetPos;
	doLogoStamper;
	doLogoConveyorClear;
	 
END_PROGRAM

PROGRAM _CYCLIC
	
	 
END_PROGRAM

PROGRAM _EXIT
	
	 
END_PROGRAM

